# Generated by Django 3.2 on 2021-12-11 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtbl',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wscdatabase.roomtype', verbose_name='Room'),
        ),
    ]
