# Generated by Django 3.2 on 2021-12-11 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0002_alter_bidtbl_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtbl',
            name='c11qty',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c11qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c12qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c12qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c13qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c13qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c14qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c14qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c15qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c15qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c21qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c21qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c22qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c22qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c23qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c23qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c24qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c24qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c25qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c25qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c31qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c31qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c32qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c32qty32', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c33qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c33qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c34qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c34qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='c35qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c35qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='cab1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab1', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='cab1num',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab1num', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='cab1sides',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab1sides', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='cab2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab2', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='cab2num',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab2num', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='cab2sides',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab2sides', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='cab3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab3', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='cab3num',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab3num', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='cab3sides',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab3sides', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp11',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp11', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp12',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp12', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp13',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp13', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp14',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp14', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp15',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp15', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp21',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp21', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp22',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp22', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp23',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp23', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp24',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp24', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp25',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp25', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp31',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp31', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp32',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp32', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp33',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp33', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp35',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp35', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='drwer1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drwer1', to='wscdatabase.numtype', to_field='num_type', verbose_name='Drawers'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='drwer2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drwer2', to='wscdatabase.numtype', to_field='num_type', verbose_name='Drawers'),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='drwer3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drwer3', to='wscdatabase.numtype', to_field='num_type', verbose_name='Drawers'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c41qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c41qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c42qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c42qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c43qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c43qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c44qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c44qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c45qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c45qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c51qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c51qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c52qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c52qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c53qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c53qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c54qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c54qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c55qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c55qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c61qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c61qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c62qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c62qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c63qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c63qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c64qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c64qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='c65qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c65qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='cab4num',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab4num', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='cab4sides',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab4sides', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='cab5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab5', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='cab5num',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab5num', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='cab5sides',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab5sides', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='cab6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab6', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='cab6num',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab6num', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='cab6sides',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cab6sides', to='wscdatabase.numtype', to_field='num_type', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp41',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp41', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp42',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp42', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp43',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp43', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp44',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp44', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp51',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp51', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp52',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp52', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp53',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp53', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp54',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp54', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp55',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp55', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp61',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp61', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp62',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp62', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp63',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp63', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp64',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp64', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp65',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp65', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='drwer4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drwer4', to='wscdatabase.numtype', to_field='num_type', verbose_name='Drawers'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='drwer5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drwer5', to='wscdatabase.numtype', to_field='num_type', verbose_name='Drawers'),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='drwer6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drwer6', to='wscdatabase.numtype', to_field='num_type', verbose_name='Drawers'),
        ),
    ]
