# Generated by Django 3.2 on 2021-12-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0003_auto_20211210_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtbl',
            name='workorderdate',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated'),
        ),
    ]
