# Generated by Django 3.2 on 2021-12-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0009_alter_totalroomcost_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalroomcost',
            name='totalperc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Percentage Increase'),
        ),
    ]
