# Generated by Django 3.2 on 2021-12-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0010_alter_totalroomcost_totalperc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtbl',
            name='comp11',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp11', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp12',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp12', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp13',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp13', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp14',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp14', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp15',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp15', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp21',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp21', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp22',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp22', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp23',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp23', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp24',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp24', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp25',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp25', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp31',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp31', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp32',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp32', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp33',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp33', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp34',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp34', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl',
            name='comp35',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp35', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp41',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp41', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp42',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp42', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp43',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp43', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp44',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp44', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp45',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp45', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp51',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp51', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp52',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp52', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp53',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp53', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp54',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp54', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp55',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp55', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp61',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp61', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp62',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp62', to='wscdatabase.comp', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp63',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp63', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp64',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp64', to='wscdatabase.cabacc', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidtbl2',
            name='comp65',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp65', to='wscdatabase.cabacc', verbose_name=''),
        ),
    ]
