# Generated by Django 3.2 on 2021-12-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0012_compoptiontotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compoptiontotal',
            old_name='totalqty',
            new_name='total_qty',
        ),
    ]
