# Generated by Django 3.2 on 2021-12-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0013_rename_totalqty_compoptiontotal_total_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoption',
            name='price',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
