# Generated by Django 3.2 on 2021-12-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0014_compoption_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='accoption',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='compoption',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
    ]
