# Generated by Django 3.2 on 2021-12-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0018_auto_20211222_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentrm',
            name='rmactive',
            field=models.BooleanField(default=True, verbose_name='Room Active'),
        ),
        migrations.AlterField(
            model_name='currentrm',
            name='rmdelete',
            field=models.BooleanField(default=False, verbose_name='Delete Room'),
        ),
    ]
