# Generated by Django 3.2 on 2021-12-28 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0020_alter_currentrm_rmnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtbl',
            name='c11qty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c11qty', to='wscdatabase.numtype', to_field='num_type', verbose_name='Qty'),
        ),
    ]
