# Generated by Django 3.2 on 2021-12-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0022_alter_bidtbl_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bidtbl',
            unique_together=set(),
        ),
    ]
