# Generated by Django 3.2 on 2022-01-02 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0024_auto_20220102_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='prodqueue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodqueue', to='wscdatabase.prodqueue', to_field='production', unique=True, verbose_name=''),
        ),
    ]
