# Generated by Django 3.2 on 2022-01-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0027_alter_customerinfo_prodqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='prodqueue',
            field=models.ForeignKey(blank=True, default='0.00', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodqueue', to='wscdatabase.prodqueue', to_field='increase', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='prodqueue',
            name='increase',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, unique=True, verbose_name='Increase'),
        ),
    ]
