# Generated by Django 3.2 on 2022-01-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0029_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='accoptiontotal',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='compoptiontotal',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
    ]
