# Generated by Django 3.2 on 2022-01-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0032_auto_20220107_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentrm',
            name='increase',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Increase'),
        ),
    ]
