# Generated by Django 3.2 on 2022-01-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0035_auto_20220107_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totals',
            name='totalincrease_currency',
        ),
        migrations.RemoveField(
            model_name='totals',
            name='totalrmcost_currency',
        ),
        migrations.AlterField(
            model_name='totals',
            name='totalincrease',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='totals',
            name='totalrmcost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Total Room Cost'),
        ),
    ]
