# Generated by Django 3.2 on 2022-01-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0038_auto_20220110_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConDelete',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('conid', models.IntegerField(default=None, null=True, verbose_name='')),
            ],
        ),
    ]
