# Generated by Django 3.2 on 2022-01-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0039_condelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidtbl',
            name='roomadd2',
            field=models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name=''),
        ),
    ]
