# Generated by Django 3.2 on 2022-01-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0040_bidtbl_roomadd2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteRm',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('deleterm', models.IntegerField(default=None, null=True, verbose_name='')),
            ],
        ),
    ]
