# Generated by Django 3.2 on 2022-01-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0041_deleterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteCust',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('deletecust', models.IntegerField(default=None, null=True, verbose_name='')),
            ],
        ),
    ]
