# Generated by Django 3.2 on 2022-01-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0042_deletecust'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='cab_labor',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='pricing',
            name='drawer_labor',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='pricing',
            name='side_labor',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
