# Generated by Django 3.2 on 2022-01-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0044_cabacc_cab_acc_labor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='cab_comp_labor',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
