# Generated by Django 3.2 on 2022-01-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0045_comp_cab_comp_labor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabacc',
            name='cab_acc_labor',
            field=models.IntegerField(default=None, null=True, verbose_name='Acc. LAbor'),
        ),
        migrations.AlterField(
            model_name='comp',
            name='cab_comp_labor',
            field=models.IntegerField(default=None, null=True, verbose_name='Comp. Labor'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='cab_labor',
            field=models.IntegerField(default=None, null=True, verbose_name='Cabinet Labor'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='drawer_labor',
            field=models.IntegerField(default=None, null=True, verbose_name='Drawer Labor'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='side_labor',
            field=models.IntegerField(default=None, null=True, verbose_name='Side Labor'),
        ),
    ]
