# Generated by Django 3.2 on 2022-01-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0046_auto_20220124_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabacc',
            name='cab_acc_labor',
            field=models.IntegerField(default=None, null=True, verbose_name='Acc. Labor'),
        ),
    ]
