# Generated by Django 3.2 on 2022-02-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0047_alter_cabacc_cab_acc_labor'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletecust',
            name='deletecon',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
