# Generated by Django 3.2 on 2022-02-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0048_deletecust_deletecon'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCost',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('bid_idA', models.IntegerField(default=None, null=True, verbose_name='')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('conid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('saleid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('totalrmcost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Cabinetry')),
                ('customtext', models.CharField(max_length=45, verbose_name='')),
                ('custom', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('discounttext', models.CharField(max_length=45, verbose_name='')),
                ('discount', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('subtotalcost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Sub Total Cost')),
                ('tax', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Tax')),
                ('totaljobcost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Total Job Cost')),
                ('constructiontext', models.CharField(max_length=45, verbose_name='')),
                ('construction', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('opt2text', models.CharField(max_length=45, verbose_name='')),
                ('opt2', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('opt3text', models.CharField(max_length=45, verbose_name='')),
                ('opt3', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
                ('install', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Install')),
                ('grandtotalcost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Grand Total Cost')),
            ],
        ),
    ]
