# Generated by Django 3.2 on 2022-02-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0050_auto_20220221_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='jobid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
