# Generated by Django 3.2 on 2022-02-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0051_jobcost_jobid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcost',
            name='bid_idA',
        ),
    ]
