# Generated by Django 3.2 on 2022-02-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0052_remove_jobcost_bid_ida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcost',
            name='customtext',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wscdatabase.contractoption', verbose_name='Custom Text'),
        ),
    ]
