# Generated by Django 3.2 on 2022-02-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0055_auto_20220222_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='taxrate',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Tax Rate'),
        ),
    ]
