# Generated by Django 3.2 on 2022-02-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0057_alter_jobcost_taxrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcost',
            name='constructiontext',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructiontext', to='wscdatabase.contractoption', verbose_name='Construction Text'),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='opt2text',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opt2text', to='wscdatabase.contractoption', verbose_name='opt2text'),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='opt3text',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opt3text', to='wscdatabase.contractoption', verbose_name='opt3text'),
        ),
    ]
