# Generated by Django 3.2 on 2022-02-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0058_auto_20220223_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='installrate',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Install'),
        ),
    ]
