# Generated by Django 3.2 on 2022-02-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0059_jobcost_installrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesNo',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('yesno', models.CharField(blank=True, max_length=50, verbose_name='Contract Option')),
            ],
        ),
    ]
