# Generated by Django 3.2 on 2022-02-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0060_yesno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcost',
            name='install',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='install', to='wscdatabase.yesno', verbose_name='Construction Text'),
        ),
    ]
