# Generated by Django 3.2 on 2022-02-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0061_alter_jobcost_install'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='cab_comp_labor',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Comp. Labor'),
        ),
    ]
