# Generated by Django 3.2 on 2022-02-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0062_alter_comp_cab_comp_labor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoption',
            name='labor',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='compoptiontotal',
            name='labor',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
    ]
