# Generated by Django 3.2 on 2022-02-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0063_auto_20220224_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comp',
            old_name='cab_comp_labor',
            new_name='labor',
        ),
    ]
