# Generated by Django 3.2 on 2022-02-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0064_rename_cab_comp_labor_comp_labor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('labor', models.IntegerField(default=None, null=True, verbose_name='')),
            ],
        ),
    ]
