# Generated by Django 3.2 on 2022-02-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0065_labor'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='bid_idA',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='labor',
            name='conid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='labor',
            name='custid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
