# Generated by Django 3.2 on 2022-02-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0070_compoption_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoption',
            name='totalprice',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
