# Generated by Django 3.2 on 2022-03-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0079_auto_20220228_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='room',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
