# Generated by Django 3.2 on 2022-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0080_labor_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborBd',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('jobid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='compoptiontotal',
            name='roomid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
