# Generated by Django 3.2 on 2022-03-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0081_auto_20220302_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compoptiontotal',
            name='roomid',
        ),
        migrations.AddField(
            model_name='compoption',
            name='roomid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
