# Generated by Django 3.2 on 2022-03-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0082_auto_20220302_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoptiontotal',
            name='roomid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
