# Generated by Django 3.2 on 2022-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0083_compoptiontotal_roomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoptiontotal',
            name='jobid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
