# Generated by Django 3.2 on 2022-03-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0084_compoptiontotal_jobid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinet',
            old_name='ident',
            new_name='cablabor',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='totalcablabor',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
