# Generated by Django 3.2 on 2022-03-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0086_cabinet_roomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborbd',
            name='room',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
