# Generated by Django 3.2 on 2022-03-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0087_laborbd_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='ident',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
