# Generated by Django 3.2 on 2022-03-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0088_cabinet_ident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinet',
            old_name='ident',
            new_name='jobid',
        ),
    ]
