# Generated by Django 3.2 on 2022-03-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0090_remove_cabinet_bidid'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoptiontotal',
            name='compname',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
    ]
