# Generated by Django 3.2 on 2022-03-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0091_compoptiontotal_compname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='cablabor',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='totalcablabor',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
    ]
