# Generated by Django 3.2 on 2022-03-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0092_auto_20220306_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoption',
            name='compname',
            field=models.CharField(max_length=45, null=True, verbose_name=''),
        ),
    ]
