# Generated by Django 3.2 on 2022-03-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0093_compoption_compname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidtbl',
            name='totalroomlabor',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
    ]
