# Generated by Django 3.2 on 2022-03-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0094_bidtbl_totalroomlabor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='drawer_labor',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='side_labor',
        ),
    ]
