# Generated by Django 3.2 on 2022-03-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0096_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclude',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('exclude', models.CharField(blank=True, max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('include', models.CharField(blank=True, max_length=50, verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='agree',
        ),
        migrations.AddField(
            model_name='agreement',
            name='agreement',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='terms',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='terms',
            name='terms',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ultimate',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ultimate',
            name='ultimate',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='worktype',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
    ]
