# Generated by Django 3.2 on 2022-03-10 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0098_auto_20220310_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='Opt1Num',
            new_name='opt1num',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='Opt1Text',
            new_name='opt1text',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='Opt2Num',
            new_name='opt2num',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='Opt2Text',
            new_name='opt2text',
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo1', to='wscdatabase.agreement', verbose_name=''),
        ),
    ]
