# Generated by Django 3.2 on 2022-03-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0099_auto_20220310_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('percent', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('multiplier', models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo10',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo10', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo11',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo11', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo12',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo12', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo13',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo13', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo14',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo14', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo15',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo15', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo16',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo16', to='wscdatabase.include', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo17',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo17', to='wscdatabase.exclude', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo2', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo3', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo4', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo5', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo6', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo7',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo7', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo8',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo8', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo9',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo9', to='wscdatabase.ultimate', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='worktype',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo2', to='wscdatabase.worktype', verbose_name=''),
        ),
    ]
