# Generated by Django 3.2 on 2022-03-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0100_auto_20220310_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='depositperc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depositperc', to='wscdatabase.percentage', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pay2perc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay2perc', to='wscdatabase.percentage', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pay3perc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay3perc', to='wscdatabase.percentage', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pay4perc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay4perc', to='wscdatabase.percentage', verbose_name=''),
        ),
    ]
