# Generated by Django 3.2 on 2022-03-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0101_auto_20220310_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement',
            field=models.CharField(blank=True, max_length=150, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='exclude',
            name='exclude',
            field=models.CharField(blank=True, max_length=150, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='include',
            name='include',
            field=models.CharField(blank=True, max_length=150, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='terms',
            name='terms',
            field=models.CharField(blank=True, max_length=150, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ultimate',
            name='ultimate',
            field=models.CharField(blank=True, max_length=150, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='worktype',
            field=models.CharField(blank=True, max_length=150, verbose_name=''),
        ),
    ]
