# Generated by Django 3.2 on 2022-03-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0102_auto_20220310_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date',
            field=models.DateField(auto_now=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='workorderdate',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated'),
        ),
    ]
