# Generated by Django 3.2 on 2022-03-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0103_auto_20220310_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclude',
            name='exclude',
            field=models.CharField(blank=True, max_length=250, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='include',
            name='include',
            field=models.CharField(blank=True, max_length=250, verbose_name=''),
        ),
    ]
