# Generated by Django 3.2 on 2022-03-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0106_auto_20220311_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedOption',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('qty', models.IntegerField(default=None, null=True, verbose_name='')),
                ('description', models.IntegerField(default=None, null=True, verbose_name='')),
            ],
        ),
    ]
