# Generated by Django 3.2 on 2022-03-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0111_accoptiontotal_accname'),
    ]

    operations = [
        migrations.AddField(
            model_name='accoption',
            name='accname',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
    ]
