# Generated by Django 3.2 on 2022-03-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0112_accoption_accname'),
    ]

    operations = [
        migrations.AddField(
            model_name='includedacc',
            name='conid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='includedoption',
            name='conid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
