# Generated by Django 3.2 on 2022-03-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0113_auto_20220313_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='conid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
