# Generated by Django 3.2 on 2022-03-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0114_contract_conid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractInclude',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('conid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('qty', models.IntegerField(default=None, null=True, verbose_name='')),
                ('includeid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='')),
            ],
        ),
    ]
