# Generated by Django 3.2 on 2022-03-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0115_contractinclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinclude',
            name='ident',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
