# Generated by Django 3.2 on 2022-03-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0118_contractinclude_pageid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractinclude',
            old_name='bidid',
            new_name='bid_idA',
        ),
    ]
