# Generated by Django 3.2 on 2022-03-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0119_rename_bidid_contractinclude_bid_ida'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractIncludeTotal',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='')),
                ('bid_idA', models.IntegerField(default=None, null=True, verbose_name='')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('conid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('pageid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('ident', models.IntegerField(default=None, null=True, verbose_name='')),
                ('qty', models.IntegerField(default=None, null=True, verbose_name='')),
                ('includeid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='')),
            ],
        ),
    ]
