# Generated by Django 3.2 on 2022-03-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0122_alter_contract_depositterms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='terms2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term2', to='wscdatabase.terms', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='terms3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term3', to='wscdatabase.terms', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='terms4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term4', to='wscdatabase.terms', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='termsfinal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termfinal', to='wscdatabase.terms', verbose_name=''),
        ),
    ]
