# Generated by Django 3.2 on 2022-03-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0126_auto_20220321_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pay2perc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay2perc', to='wscdatabase.percentage', to_field='multiplier', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pay3perc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay3perc', to='wscdatabase.percentage', to_field='multiplier', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pay4perc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay4perc', to='wscdatabase.percentage', to_field='multiplier', verbose_name=''),
        ),
    ]
