# Generated by Django 3.2 on 2022-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0127_auto_20220321_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='depositdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='finalpaymentdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment2date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment3date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment4date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
