# Generated by Django 3.2 on 2022-03-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0129_auto_20220323_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='taxperc',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
    ]
