# Generated by Django 3.2 on 2022-03-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0130_taxrate_taxperc'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcost',
            name='installtext',
            field=models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name=''),
        ),
    ]
