# Generated by Django 3.2 on 2022-03-25 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0131_jobcost_installtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcost',
            name='install',
            field=models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='jobcost',
            name='installtext',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='install', to='wscdatabase.yesno', verbose_name='Construction Text'),
        ),
    ]
