# Generated by Django 3.2 on 2022-03-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0132_auto_20220324_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='roomactive',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
