# Generated by Django 3.2 on 2022-03-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0133_labor_roomactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labor',
            old_name='roomactive',
            new_name='rmactive',
        ),
        migrations.AddField(
            model_name='bidtbl',
            name='rmactive',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
