# Generated by Django 3.2 on 2022-03-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0135_totalroomcost_rmactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractincludetotal',
            name='rmactive',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
