# Generated by Django 3.2 on 2022-03-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0136_contractincludetotal_rmactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractincludetotal',
            name='bid_idA',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
