# Generated by Django 3.2 on 2022-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0137_contractincludetotal_bid_ida'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinclude',
            name='rmactive',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
