# Generated by Django 3.2 on 2022-03-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0139_contractincludetotal_includeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalroomcost',
            name='room',
            field=models.CharField(max_length=45, verbose_name='Address #1:'),
        ),
    ]
