# Generated by Django 3.2 on 2022-03-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0141_auto_20220326_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalroomcost',
            name='door',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address #1:'),
        ),
        migrations.AddField(
            model_name='totalroomcost',
            name='fncolor',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address #1:'),
        ),
        migrations.AddField(
            model_name='totalroomcost',
            name='fnoption',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address #1:'),
        ),
        migrations.AddField(
            model_name='totalroomcost',
            name='wood',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address #1:'),
        ),
    ]
