# Generated by Django 3.2 on 2022-04-01 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0142_auto_20220326_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtbl',
            name='comp32',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp32', to='wscdatabase.comp', verbose_name=''),
        ),
    ]
