# Generated by Django 3.2 on 2022-04-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0144_auto_20220401_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidtbl2',
            name='idA',
            field=models.IntegerField(default=None, null=True, verbose_name='page ID.'),
        ),
    ]
