# Generated by Django 3.2 on 2022-04-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0145_bidtbl2_ida'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoption',
            name='pageid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
