# Generated by Django 3.2 on 2022-04-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0146_compoption_pageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoption',
            name='idA',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
