# Generated by Django 3.2 on 2022-04-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0147_compoption_ida'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinclude',
            name='idA',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
