# Generated by Django 3.2 on 2022-04-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0148_contractinclude_ida'),
    ]

    operations = [
        migrations.AddField(
            model_name='accoptiontotal',
            name='roomid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
