# Generated by Django 3.2 on 2022-04-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0150_auto_20220403_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='accoption',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
    ]
