# Generated by Django 3.2 on 2022-04-03 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0151_accoption_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractinclude',
            name='bidid',
        ),
    ]
