# Generated by Django 3.2 on 2022-04-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0152_remove_contractinclude_bidid'),
    ]

    operations = [

    ]
