# Generated by Django 3.2 on 2022-04-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0153_auto_20220410_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ultimate',
            options={'verbose_name': 'Work Type List'},
        ),
        migrations.RemoveField(
            model_name='cabacc',
            name='cab_acc_labor',
        ),
        migrations.AlterField(
            model_name='prodqueue',
            name='increase',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, unique=True, verbose_name='Increase / Decrease'),
        ),
        migrations.AlterModelTable(
            name='ultimate',
            table='Ultimate',
        ),
    ]
