# Generated by Django 3.2 on 2022-04-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0155_auto_20220410_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comp',
            options={'verbose_name': 'Cabinet Option'},
        ),
        migrations.AlterModelTable(
            name='comp',
            table='Comp',
        ),
    ]
