# Generated by Django 3.2 on 2022-04-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0156_auto_20220410_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woodspecies',
            options={'verbose_name': 'Wood Specie'},
        ),
        migrations.AlterModelTable(
            name='woodspecies',
            table='WoodSpecies',
        ),
    ]
