# Generated by Django 3.2 on 2022-04-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0157_auto_20220410_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Work Type'},
        ),
        migrations.AlterModelTable(
            name='worktype',
            table='WorkType',
        ),
    ]
