# Generated by Django 3.2 on 2022-04-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0158_auto_20220410_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='agreementlist',
            field=models.CharField(blank=True, max_length=250, verbose_name=''),
        ),
    ]
