# Generated by Django 3.2 on 2022-04-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0159_contract_agreementlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='excludedescr',
            field=models.CharField(blank=True, max_length=250, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='includedescr',
            field=models.CharField(blank=True, max_length=250, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='worktypedescr',
            field=models.CharField(blank=True, max_length=250, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='worktypelistdescr',
            field=models.CharField(blank=True, max_length=250, verbose_name=''),
        ),
    ]
