# Generated by Django 3.2 on 2022-04-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0160_auto_20220410_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='worktype',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
