# Generated by Django 3.2 on 2022-04-10 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0161_alter_contract_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='worktype',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktype1', to='wscdatabase.worktype', verbose_name=''),
        ),
    ]
