# Generated by Django 3.2 on 2022-04-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0162_alter_contract_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='worktype',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
