# Generated by Django 3.2 on 2022-04-15 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0164_alter_contract_worktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalroomcost',
            name='finishoption2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp25', to='wscdatabase.finishoption', verbose_name='Finish Option'),
        ),
        migrations.AddField(
            model_name='totalroomcost',
            name='finishoption2perc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name=''),
        ),
        migrations.AddField(
            model_name='totalroomcost',
            name='fnoption2',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Address #1:'),
        ),
    ]
