# Generated by Django 3.2 on 2022-04-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0165_auto_20220415_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='totals',
            name='cabaccrmtotal',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Room Cost'),
        ),
        migrations.AddField(
            model_name='totals',
            name='optionnum',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name='Room Cost'),
        ),
    ]
