# Generated by Django 3.2 on 2022-04-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0166_auto_20220421_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='totals',
            name='cabaccrmtotalincrease',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='totals',
            name='cabaccrmtotaltotal',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='totals',
            name='optionnumincrease',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='totals',
            name='optionnumtotal',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='totals',
            name='cabaccrmtotal',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='totals',
            name='optionnum',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
    ]
