# Generated by Django 3.2 on 2022-04-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0167_auto_20220422_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='totals',
            name='baseprice',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7, verbose_name=''),
        ),
    ]
